### ISSUE TITLE
[BUG] blog single full width: thumbnail max-width on mobile

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#137]
Hello

Using OceanWP version 1.5.28, my images with thumbnail class are too wide on mobile.
See the screenshot.

![blogsinglemaxwidth-thumbnail](https://user-images.githubusercontent.com/108828/46852495-7e0bfb80-cdfb-11e8-8b3b-eb0a44f230c1.PNG)

```css
.single-post.content-max-width .thumbnail{
max-width: 1140px;
}
```
is applied and my image is 1024px wide so it is too large.
I guess the `max-width: 1140px;` should be applied only after a certain breakpoint.

Thanks
