### ISSUE TITLE
Customize forms select

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#37]
When customizing forms (in Customize > General options > Forms (input - textarea), changing the background color, it only applies to input and textarea.

The generated CSS is:
```css
form input[type="text"], 
form input[type="password"], 
form input[type="email"], 
form input[type="tel"], 
form input[type="url"], 
form input[type="search"], 
form textarea {
    background-color: #ffffff;
}
```

But the default OceanWP styles are:
```css
form input[type="text"], 
form input[type="password"], 
form input[type="email"], 
form input[type="url"], 
form input[type="date"], 
form input[type="month"], 
form input[type="time"], 
form input[type="datetime"], 
form input[type="datetime-local"], 
form input[type="week"], 
form input[type="number"], 
form input[type="search"], 
form input[type="tel"], 
form input[type="color"], 
form select, 
form textarea{
    display: inline-block;
    min-height: 40px;
    width: 100%;
    font-size: 14px;
    line-height: 1.8;
    padding: 6px 12px;
    vertical-align: middle;
    background-color: transparent;
    color: #333;
    border: 1px solid #ddd;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    -ms-border-radius: 3px;
    border-radius: 3px;
    -webkit-transition: all 0.3s ease;
    -moz-transition: all 0.3s ease;
    -ms-transition: all 0.3s ease;
    -o-transition: all 0.3s ease;
    transition: all 0.3s ease;
}
```

As you can see, `form select, form input[type="date/month/time/datetime/datetime-local/week/number/color"]` are not recieving the customized background color.
Is it possible to include `select`?

Thank you
Nico from Saint-Malo
