### ISSUE TITLE
Flex CSS rules not valid once minified

### ISSUE THREAD

**Issue by nicomollet** [oceanwp/oceanwp#43]
Hello (again),
It looks some CSS generated by OceanWP is not valid/standard.

See my website https://www.restaurant-caphorn.fr/, it has WP Rocket and Minify active.

The following CSS is generated by OceanWP on the main logo (works on Chrome lastest version):
```css
#site-header.medium-header .top-col.logo-col{
    -webkit-flex: auto 0 0;
    flex: auto 0 0;
}
```

which once minified/compressed and is becoming (doesn't not work on Chrome lastest version):
```css
#site-header.medium-header .top-col.logo-col {
    -webkit-flex: auto 0 0%;
    flex: auto 0 0%;
}
```

`flex: auto 0 0%;` is not valid CSS, so it breaks the alignment. (FYI I overrided the rule on my website to fix it).
Minify author told me the original CSS from OceanWP `flex: auto 0 0;` is not standard. See his explaination on https://github.com/matthiasmullie/minify/issues/235

What to you think?
Nico
